language: scala
jdk: oraclejdk8

matrix:
  include:
   - scala: 2.10.7
     env: CMD="mimaReportBinaryIssues scalafmt::test test:scalafmt::test sbt:scalafmt::test test"

   - scala: 2.11.12
     env: CMD="mimaReportBinaryIssues scalafmt::test test:scalafmt::test sbt:scalafmt::test test"

   - scala: 2.12.4
     env: CMD="mimaReportBinaryIssues scalafmt::test test:scalafmt::test sbt:scalafmt::test test"

   - scala: 2.13.0-M2
     env: CMD=compile

script: sbt ++$TRAVIS_SCALA_VERSION $CMD

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
