name: CI
on:
  pull_request:
  push:

env:
  SCALA212: 2.12.*
  SCALA213: 2.13.*
  SCALA3: 3.1.*

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            jobtype: 1
          - os: ubuntu-latest
            java: 11
            jobtype: 2
          - os: macos-latest
            java: 8
            jobtype: 2
          - os: windows-latest
            java: 8
            jobtype: 2
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - name: Coursier cache
      uses: coursier/cache-action@v5
    - name: Install the original sbt
      shell: bash
      run: |
        RUNNER_VER=1.5.5
        curl -sL https://raw.githubusercontent.com/sbt/sbt/v$RUNNER_VER/sbt > $HOME/bin/sbt
    - name: Build and test
      shell: bash
      run: |
        case ${{ matrix.jobtype }} in
          1)
            sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=true ++$SCALA212 mimaReportBinaryIssues scalafmtCheckAll headerCheck Test/headerCheck test doc
            sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=false ++$SCALA213 test ++$SCALA3 test
            ;;
          2)
            sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=true ++$SCALA212 mimaReportBinaryIssues test
            sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=false ++$SCALA213 test ++$SCALA3 test
            ;;
          *)
            echo unknown jobtype
            exit 1
        esac
        rm -rf "$HOME/.ivy2/local"
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true
